medical_segmentation/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

medical_segmentation/data_preparation/urls.py
from django.urls import path
from . import views

app_name = 'data_preparation'
urlpatterns = [
    path('upload-multiple/', views.upload_multiple_images, name='upload_multiple_images'),
    path('frame-sequences/', views.frame_sequence_list, name='frame_sequence_list'),
    path('upload-video/', views.upload_video, name='upload_video'),
    path('get_videos/', views.get_videos, name='get_videos'),
    path('delete-video/', views.delete_video, name='delete_video'),
    path('create-frame-sequence/<str:video_id>/', views.create_frame_sequence, name='create_frame_sequence'),
    path('view-frame-sequence/<str:video_id>/', views.view_frame_sequence, name='view_frame_sequence'),
    path('sequence/<int:sequence_id>/delete/', views.delete_sequence, name='delete_sequence'),
    path('', views.TagListView.as_view(), name='tag_list'),
    path('add/', views.TagCreateView.as_view(), name='tag_add'),
    path('<int:pk>/edit/', views.TagUpdateView.as_view(), name='tag_edit'),
    path('<int:pk>/delete/', views.TagDeleteView.as_view(), name='tag_delete'),   
    path("prepare-dataset/", views.prepare_dataset_view, name="prepare_dataset"), 
    path('delete-dataset/<int:dataset_id>/', views.delete_dataset, name='delete-dataset'),
    path('download-dataset/<int:dataset_id>/', views.download_dataset, name='download-dataset'),
]

medical_segmentation/medical_segmentation/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

# Подключение маршрутов для i18n
urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('about.urls')),
    path('', include('data_preparation.urls')),
    path('', include('segmentation.urls')),
    path('', include('nettrain.urls')),
    path('', include('view_result.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medical_segmentation/nettrain/urls.py
from django.urls import path
from . import views

app_name = 'nettrain'
urlpatterns = [
    path('start_training/', views.start_training_view, name='start_training'),
    path('delete-model/<int:model_id>/', views.delete_model, name='delete-model'),
    path('download-model/<int:model_id>/', views.download_model, name='download-model'),
]

medical_segmentation/view_result/urls.py
from django.urls import path
from . import views

app_name = 'view_result'  # Задайте имя пространства имён

urlpatterns = [
    path('view_video/', views.view_video, name='view_video'),
]

medical_segmentation/templates/includes/footer.html
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
      <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
         

medical_segmentation/templates/includes/header.html
{% load static %}
{% load i18n %}
{% load custom_tags %}
<nav id="navbar" class="navbar navbar-expand-lg {% if request.COOKIES.theme == 'dark' %}dark-mode{% else %}navbar-light bg-light{% endif %}">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'about:tech' %}">{% trans "About" %}</a>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link {% if request.path == '/data_preparation/upload_multiple_images/' %}active{% endif %}" href="{% url 'data_preparation:upload_multiple_images' %}">
            {% trans "Upload Multiple Images" %}
          </a>
        </li>         
        <li class="nav-item">
          <a class="nav-link {% if request.path == '/data-preparation/upload-video/' %}active{% endif %}" href="{% url 'data_preparation:upload_video' %}">
            {% trans "Upload Video" %}
          </a>
        </li>        
        <li class="nav-item">
          <a class="nav-link {% if request.path == '/data-preparation/frame-sequence-list/' %}active{% endif %}" href="{% url 'data_preparation:frame_sequence_list' %}">
            {% trans "Image List" %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == '/data-preparation/tag-list/' %}active{% endif %}" href="{% url 'data_preparation:tag_list' %}">
            {% trans "Tags" %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == '/nettrain/start-training/' %}active{% endif %}" href="{% url 'data_preparation:prepare_dataset' %}">
            {% trans "Prepare dataset" %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == '/nettrain/start-training/' %}active{% endif %}" href="{% url 'nettrain:start_training' %}">
            {% trans "Train Model" %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == '/view-result/view-video/' %}active{% endif %}" href="{% url 'view_result:view_video' %}">
            {% trans "Result" %}
          </a>
        </li>        
      </ul>
      <form action="{% url 'set_language' %}" method="post" class="d-flex">
        {% csrf_token %}
        <select name="language" class="form-select me-2" onchange="this.form.submit()">
          <option value="en" {% if LANGUAGE_CODE == 'en' %}selected{% endif %}>English</option>
          <option value="ru" {% if LANGUAGE_CODE == 'ru' %}selected{% endif %}>Русский</option>
        </select>
      </form>
      <button id="theme-toggle" class="btn btn-outline-secondary ms-2">
        {% if request.COOKIES.theme == 'dark' %}Light Mode{% else %}Dark Mode{% endif %}
      </button>
    </div>
  </div>
</nav>